@if (Request::is('admin-subscriber'))
    @include('inc/navbar/admin.subscriber')
@elseif(Request::is('admin-shop'))
    @include('inc/navbar/admin.shop')
@elseif(Request::is('admin-music'))
    @include('inc/navbar/admin.music')
@elseif(Request::is('admin-dashboard'))
    @include('inc/navbar/admin.dashboard')
@elseif(Request::is('admin-shop/create'))
    @include('inc/navbar/admin.shop')
@elseif(Request::is('admin-music/create'))
    @include('inc/navbar/admin.music')
@elseif(Request::is('admin-video'))
    @include('inc/navbar/admin.video')
@elseif(Request::is('admin-video/create'))
    @include('inc/navbar/admin.video')
@endif
